[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://singolo-aleksey-vl-ivanov.netlify.app/*"
  to = "https://singolo.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://singolo-aleksey-vl-ivanov.netlify.app/*"
  to = "https://singolo.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://singolo.aleksey-vl-ivanov.com/*"
  to = "https://singolo.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true
